Rearranged job report email body
vendanor/CloudDump pull request #45
Opened 2023-05-22 22:26 UTC by ralftar

Remember version bump if not taking in other cahnges at the same time (e.g. https://github.com/vendanor/CloudDump/pull/44)

2023-05-23 07:23 UTC, ralftar commented
My minutes seconds calculation failed. can you have a look at it @jonaski ?

2023-05-30 06:08 UTC, jonaski requested changes

2023-05-30 06:08 UTC, jonaski commented on scripts/wrapper.sh
> +Time elapsed: $((time_end - time_start)/60) minutes $((time_end - time_start)%60) seconds
```suggestion
Time elapsed: $(((time_end - time_start)/60)) minutes $(((time_end - time_start)%60)) seconds
```

2023-05-30 08:55 UTC, jonaski requested changes

2023-05-30 08:55 UTC, jonaski commented on scripts/wrapper.sh
> +Confiugration:
```suggestion
Configuration:
```

2023-05-30 09:00 UTC, ralftar commented
Can you go ahead and complete this PR and https://github.com/vendanor/CloudDump/pull/44 into a new release @jonaski ?

2023-05-30 09:26 UTC, jonaski approved these changes

2023-05-30 09:29 UTC, merged